# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findIndices_char_glo <- function(vec, target) {
    .Call(`_iClusterVB_findIndices_char_glo`, vec, target)
}

findIndex_numeric_glo <- function(vec, target) {
    .Call(`_iClusterVB_findIndex_numeric_glo`, vec, target)
}

softmax_log_glo <- function(log_values) {
    .Call(`_iClusterVB_softmax_log_glo`, log_values)
}

countValues_glo <- function(vector, U) {
    .Call(`_iClusterVB_countValues_glo`, vector, U)
}

ddirichlet_glo <- function(x, alpha) {
    .Call(`_iClusterVB_ddirichlet_glo`, x, alpha)
}

log_ddirichlet_glo <- function(x, alpha) {
    .Call(`_iClusterVB_log_ddirichlet_glo`, x, alpha)
}

CAVI_algorithm_global <- function(mydata, data_summary, hyper_parameters, initial_values, dist, K, max_iter, early_stop, per, epsilon, convergence_threshold) {
    .Call(`_iClusterVB_CAVI_algorithm_global`, mydata, data_summary, hyper_parameters, initial_values, dist, K, max_iter, early_stop, per, epsilon, convergence_threshold)
}

findIndices_char <- function(vec, target) {
    .Call(`_iClusterVB_findIndices_char`, vec, target)
}

findIndex_numeric <- function(vec, target) {
    .Call(`_iClusterVB_findIndex_numeric`, vec, target)
}

softmax_log <- function(log_values) {
    .Call(`_iClusterVB_softmax_log`, log_values)
}

countValues <- function(vector, U) {
    .Call(`_iClusterVB_countValues`, vector, U)
}

ddirichlet <- function(x, alpha) {
    .Call(`_iClusterVB_ddirichlet`, x, alpha)
}

log_ddirichlet <- function(x, alpha) {
    .Call(`_iClusterVB_log_ddirichlet`, x, alpha)
}

CAVI_algorithm_standard <- function(mydata, data_summary, hyper_parameters, initial_values, dist, K, max_iter, early_stop, per, epsilon, convergence_threshold) {
    .Call(`_iClusterVB_CAVI_algorithm_standard`, mydata, data_summary, hyper_parameters, initial_values, dist, K, max_iter, early_stop, per, epsilon, convergence_threshold)
}

